"""HTML report generation with Peach Studio styling.

Generates a self-contained HTML report for MRRA — Mainframe Ransomware
Readiness Assessment. Checks are grouped by NIST CSF function to align
with the 10-dimension assessment framework.
"""

from pathlib import Path
from typing import Any

from znextscan.scanner import ScanResult

STATUS_COLORS = {
    "Pass": "#22C55E",
    "Partial": "#F59E0B",
    "Fail": "#EF4444",
    "Error": "#8B5CF6",
    "Skipped": "#9CA3AF",
}

STATUS_ICONS = {
    "Pass": "&#10003;",
    "Partial": "&#9888;",
    "Fail": "&#10007;",
    "Error": "&#9889;",
    "Skipped": "&#8212;",
}

# Map control ID prefixes to NIST CSF functions
NIST_FUNCTIONS: list[tuple[str, str, str, list[str]]] = [
    ("F1", "Asset Inventory & Risk", "IDENTIFY", ["ID"]),
    ("F2", "Identity & Access Management", "PROTECT", ["IAM"]),
    ("F3", "Data Protection & Encryption", "PROTECT", ["ENC"]),
    ("F7", "Monitoring, Detection & Response", "DETECT", ["MON"]),
    ("F11", "System Core Integrity", "PROTECT", ["SCI"]),
    ("EXT", "Extended Security Checks", "ASSESS", ["EXT"]),
]


# Mythos dimension -> (group id, group name, NIST category)
MYTHOS_DIMENSIONS: dict[str, tuple[str, str, str]] = {
    "R": ("R", "Preparedness & Readiness", "IDENTIFY"),
    "C": ("C", "Controls to Add", "PROTECT"),
    "V": ("V", "Vulnerability Patching", "IDENTIFY"),
    "X": ("X", "Response & Recovery", "RESPOND/RECOVER"),
}


def _get_function_for_check(control_id: str) -> tuple[str, str, str]:
    """Return (function_id, function_name, nist_category) for a control ID."""
    parts = control_id.split("-")
    prefix = parts[0]
    if prefix == "MYT" and len(parts) > 1 and parts[1][:1] in MYTHOS_DIMENSIONS:
        return MYTHOS_DIMENSIONS[parts[1][0]]
    for fid, fname, nist, prefixes in NIST_FUNCTIONS:
        if prefix in prefixes:
            return fid, fname, nist
    return "OTHER", "Other Checks", "ASSESS"


def generate_html_report(scan: ScanResult) -> str:
    """Generate a self-contained HTML report from scan results."""
    d = scan.to_dict()
    meta = d["scan_metadata"]
    summary = d["summary"]
    controls = d["controls"]

    # Group checks by NIST function
    grouped = _group_by_function(controls)
    sections_html = "\n".join(
        _render_function_section(fid, fname, nist, checks) for fid, fname, nist, checks in grouped
    )

    summary_cards = _render_summary(summary)
    score_gauge = _render_score_gauge(summary["score_pct"])
    threat_context = _render_threat_context(summary)

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>MRRA Report — Mainframe Ransomware Readiness Assessment</title>
<style>
{_get_css()}
</style>
</head>
<body>
<div class="container">

  <header class="report-header">
    <div class="header-brand">MRRA SCANNER</div>
    <h1 class="report-title">Mainframe Ransomware Readiness Assessment</h1>
    <p class="report-subtitle">Automated Security Configuration Analysis</p>
    <div class="meta-row">
      <span class="meta-item">Scan ID: <strong>{meta['scan_id'][:8]}</strong></span>
      <span class="meta-item">Date: <strong>{meta['start_time'][:10]}</strong></span>
      <span class="meta-item">Method: <strong>{meta['connection_method'].upper()}</strong></span>
      <span class="meta-item">Duration: <strong>{meta.get('duration_seconds', 0):.1f}s</strong></span>
    </div>
  </header>

  <section class="score-section">
    {score_gauge}
    <div class="summary-cards">
      {summary_cards}
    </div>
  </section>

  {threat_context}

  <section class="checks-section">
    <h2 class="section-title">Assessment Results by NIST CSF Function</h2>
    <p class="section-subtitle">Automated checks across NIST Cybersecurity Framework dimensions, focused on ransomware resilience.</p>
    {sections_html}
  </section>

  <footer class="report-footer">
    <p>Generated by zNextScan v{meta['scanner_version']}</p>
    <p class="footer-note">This report covers scanner-automated checks. Interview-based controls (MFA, backup, DR, IR, training, third-party) require workshop validation.</p>
    <p class="footer-note">Handle according to your organization's data classification policies.</p>
  </footer>

</div>
</body>
</html>"""


def write_html_report(scan: ScanResult, output_path: str | Path) -> Path:
    """Write HTML report to a file. Returns the path written."""
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(generate_html_report(scan))
    return path


def _group_by_function(
    controls: list[dict[str, Any]],
) -> list[tuple[str, str, str, list[dict[str, Any]]]]:
    """Group controls by NIST function, preserving order."""
    groups: dict[str, tuple[str, str, list[dict[str, Any]]]] = {}
    for check in controls:
        fid, fname, nist = _get_function_for_check(check["control_id"])
        if fid not in groups:
            groups[fid] = (fname, nist, [])
        groups[fid][2].append(check)
    return [(fid, fname, nist, checks) for fid, (fname, nist, checks) in groups.items()]


def _render_threat_context(summary: dict[str, Any]) -> str:
    score = summary["score_pct"]
    if score >= 70:
        level, color, desc = (
            "MODERATE",
            "#F59E0B",
            "Foundational controls are in place but gaps remain that could be exploited in a targeted ransomware attack.",
        )
    elif score >= 40:
        level, color, desc = (
            "HIGH",
            "#EF4444",
            "Significant gaps in ransomware defenses detected. Critical controls are missing or misconfigured.",
        )
    else:
        level, color, desc = (
            "CRITICAL",
            "#DC2626",
            "Severe deficiencies in ransomware readiness. Immediate remediation required.",
        )

    if score >= 80:
        level, color, desc = (
            "LOW",
            "#22C55E",
            "Strong ransomware readiness posture. Minor improvements recommended.",
        )

    return f"""
  <section class="threat-section">
    <div class="threat-card">
      <div class="threat-header">
        <span class="threat-level" style="background: {color}">{level} RISK</span>
        <span class="threat-title">Ransomware Readiness Posture</span>
      </div>
      <p class="threat-desc">{desc}</p>
      <p class="threat-context">This assessment evaluates your IBM Z mainframe's resilience against the 6 STRIDE/DREAD threat scenarios: credential spoofing, APF library tampering, audit log manipulation, data exfiltration, batch job ransomware, and backup compromise.</p>
    </div>
  </section>"""


def _render_summary(summary: dict[str, Any]) -> str:
    items = [
        ("Passed", summary["passed"], "#22C55E"),
        ("Partial", summary["partial"], "#F59E0B"),
        ("Failed", summary["failed"], "#EF4444"),
        ("Errors", summary["errors"], "#8B5CF6"),
        ("Skipped", summary["skipped"], "#9CA3AF"),
    ]
    return "".join(
        f'<div class="summary-card"><div class="summary-count" style="color: {c}">{n}</div>'
        f'<div class="summary-label">{l}</div></div>'
        for l, n, c in items
    )


def _render_score_gauge(score: float) -> str:
    color = "#22C55E" if score >= 70 else "#F59E0B" if score >= 40 else "#EF4444"
    return f"""
    <div class="score-gauge">
      <div class="score-box" style="border-color: {color}">
        <div class="score-value" style="color: {color}">{score:.0f}%</div>
        <div class="score-label">Readiness Score</div>
      </div>
    </div>"""


def _render_function_section(fid: str, fname: str, nist: str, checks: list[dict[str, Any]]) -> str:
    passed = sum(1 for c in checks if c["status"] == "Pass")
    total = len(checks)
    checks_html = "\n".join(_render_check(c) for c in checks)
    return f"""
    <div class="function-group">
      <div class="function-header">
        <span class="function-badge">{nist}</span>
        <span class="function-name">{fname}</span>
        <span class="function-score">{passed}/{total} passed</span>
      </div>
      <div class="checks-list">
        {checks_html}
      </div>
    </div>"""


def _render_check(check: dict[str, Any]) -> str:
    status = check["status"]
    color = STATUS_COLORS.get(status, "#9CA3AF")
    icon = STATUS_ICONS.get(status, "?")
    findings_html = ""
    if check["findings"]:
        items = "".join(f"<li>{_escape(f)}</li>" for f in check["findings"])
        findings_html = f'<ul class="findings-list">{items}</ul>'

    error_html = ""
    if check.get("error"):
        error_html = f'<div class="check-error">{_escape(check["error"])}</div>'

    return f"""
    <div class="check-card">
      <div class="check-header">
        <span class="status-badge" style="background-color: {color}">{icon} {status}</span>
        <span class="check-id">{check['control_id']}</span>
        <span class="check-name">{_escape(check['control_name'])}</span>
      </div>
      {findings_html}
      {error_html}
    </div>"""


def _escape(text: str) -> str:
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def _get_css() -> str:
    return """
/* MRRA Report — Peach Studio Design Language */
/* PDF-compatible: no clamp(), conic-gradient, box-shadow, or bare @media */
* { margin: 0; padding: 0; box-sizing: border-box; }

body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
    font-size: 16px;
    line-height: 1.6;
    color: #1F1F1F;
    background: #FAF9F7;
}

.container {
    max-width: 960px;
    margin: 0 auto;
    padding: 24px;
}

.report-header {
    text-align: center;
    padding: 48px 0 24px;
}

.header-brand {
    font-size: 13px;
    font-weight: 700;
    color: #FF6B35;
    text-transform: uppercase;
    letter-spacing: 2px;
    margin-bottom: 8px;
}

.report-title {
    font-size: 34px;
    font-weight: 700;
    color: #1F1F1F;
    letter-spacing: -0.02em;
    margin-bottom: 4px;
}

.report-subtitle {
    font-size: 16px;
    color: #9CA3AF;
    margin-bottom: 20px;
}

.meta-row {
    text-align: center;
    font-size: 14px;
    color: #9CA3AF;
}

.meta-item {
    margin: 0 8px;
}

.meta-item strong { color: #1F1F1F; }

/* Score */
.score-section {
    text-align: center;
    padding: 24px 0;
}

.score-gauge { margin-bottom: 24px; }

.score-box {
    display: inline-block;
    border: 4px solid #22C55E;
    border-radius: 16px;
    padding: 20px 40px;
    text-align: center;
}

.score-value {
    font-size: 48px;
    font-weight: 700;
}

.score-label {
    font-size: 12px;
    color: #9CA3AF;
    text-transform: uppercase;
    letter-spacing: 1px;
    margin-top: 2px;
}

.summary-cards {
    text-align: center;
}

.summary-card {
    display: inline-block;
    background: #FFFFFF;
    border-radius: 12px;
    padding: 14px 20px;
    min-width: 90px;
    border: 1px solid #E5E7EB;
    margin: 4px;
}

.summary-count { font-size: 26px; font-weight: 700; }
.summary-label { font-size: 12px; color: #9CA3AF; font-weight: 500; }

/* Threat */
.threat-section { padding: 16px 0 24px; }

.threat-card {
    background: #FFFFFF;
    border-radius: 12px;
    padding: 20px 24px;
    border: 1px solid #E5E7EB;
}

.threat-header {
    margin-bottom: 10px;
}

.threat-level {
    display: inline-block;
    color: white;
    font-size: 11px;
    font-weight: 700;
    padding: 4px 10px;
    border-radius: 6px;
    letter-spacing: 0.5px;
    margin-right: 10px;
}

.threat-title { font-weight: 600; font-size: 17px; color: #1F1F1F; }
.threat-desc { font-size: 15px; color: #1F1F1F; margin-bottom: 8px; line-height: 1.6; }
.threat-context { font-size: 13px; color: #9CA3AF; line-height: 1.6; }

/* Checks */
.checks-section { padding: 16px 0; }

.section-title {
    font-size: 22px;
    font-weight: 700;
    color: #1F1F1F;
    margin-bottom: 6px;
}

.section-subtitle {
    font-size: 14px;
    color: #9CA3AF;
    margin-bottom: 24px;
}

.function-group { margin-bottom: 24px; }

.function-header {
    padding: 10px 0;
    border-bottom: 2px solid #F3F4F6;
    margin-bottom: 10px;
}

.function-badge {
    display: inline-block;
    font-size: 10px;
    font-weight: 700;
    color: #FF6B35;
    background: #FFF5F0;
    padding: 3px 8px;
    border-radius: 4px;
    text-transform: uppercase;
    letter-spacing: 0.5px;
    margin-right: 8px;
}

.function-name { font-size: 16px; font-weight: 600; color: #1F1F1F; }
.function-score { font-size: 13px; color: #9CA3AF; font-weight: 500; float: right; }

.checks-list {
    margin: 0;
}

.check-card {
    background: #FFFFFF;
    border-radius: 10px;
    padding: 14px 18px;
    border: 1px solid #F3F4F6;
    margin-bottom: 8px;
}

.check-header {
    margin: 0;
}

.status-badge {
    display: inline-block;
    color: white;
    font-size: 11px;
    font-weight: 600;
    padding: 3px 9px;
    border-radius: 5px;
    min-width: 68px;
    text-align: center;
    margin-right: 8px;
}

.check-id {
    font-size: 12px;
    font-weight: 600;
    color: #FF6B35;
    font-family: 'Courier New', monospace;
    margin-right: 8px;
}

.check-name { font-weight: 600; font-size: 14px; color: #1F1F1F; }

.findings-list {
    margin-top: 8px;
    padding-left: 18px;
    font-size: 13px;
    color: #9CA3AF;
    line-height: 1.6;
}

.findings-list li { margin-bottom: 1px; }

.check-error {
    margin-top: 6px;
    padding: 6px 10px;
    background: #FEF2F2;
    color: #DC2626;
    border-radius: 5px;
    font-size: 12px;
}

/* Footer */
.report-footer {
    text-align: center;
    padding: 28px 0 16px;
    font-size: 13px;
    color: #9CA3AF;
    border-top: 1px solid #E5E7EB;
    margin-top: 24px;
}

.footer-note { margin-top: 4px; font-size: 12px; opacity: 0.7; }

@media print {
    body { background: white; }
    .container { max-width: 100%; }
}
"""
